ADD_USER = "admin.add_user"
SERVER_INFO = "admin.server_info"
ADMIN_USER = "admin.admin_users"
USER_ENABLE = "admin.user.enable"
USER_DISABLE = "admin.user.disable"
USER_DELETE = "admin.user.delete"
USER_RESET_DAYS = "admin.user.reset_days"
USER_RESET_USAGE = "admin.user.reset_usage"
